CREATE TABLE [dbo].[tblAlert]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [AlertingId] UNIQUEIDENTIFIER NOT NULL, 
    [BeingAlertedId] UNIQUEIDENTIFIER NOT NULL, 
    [Description] VARCHAR(255) NOT NULL, 
    [AlertDate] DATETIME NOT NULL, 
    [Status] VARCHAR(50) NOT NULL, 
    [EquipmentId] UNIQUEIDENTIFIER NOT NULL, 
    [StationId] UNIQUEIDENTIFIER NOT NULL
)
